image: python:3.9-slim

before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - apt-get update && apt-get install -y git
  - pip install mkdocs~=1.0.4
  - pip install mkdocs-git-revision-date-localized-plugin~=0.11.0
  - pip install mkdocs-material~=8.0
  - pip install mkdocs-exclude
  - pip install mkdocs-exclude

stages:
- deploy

pages:
  stage: deploy
  tags:
   - hva
  variables:
    ENABLED_GIT_REVISION_DATE: "true"
    GIT_DEPTH: 1000
  script:
  - sh ./scripts/update-index-docs.sh
  - mkdocs build --site-dir public
  artifacts:
    paths:
    - public
  only:
    - development
    - production
    - feature/documentation
    - patch/continuous-integration
